### ISSUE TITLE
[i8n]bierbogen

### ISSUE THREAD

**Issue by zh0uquan** [sahib/misc#1]
I like the beer rating sheet!!! Have you thought about making it friendly to be more international?

**Comment by sahib** [comment]
Hey @zh0uquan! :smirk:

We could do that. The translation will be a bit tricky though since there are also a few jokes (also some inside jokes) that are hard to translate / some words I definitely need to lookup. Also the translation will yield in slightly different layout. I can try to translate it when I find the time.

Feel free to post something again if you don't hear from me.

**Comment by sahib** [comment]
@zh0uquan : Lucky you, I had a few minutes: https://github.com/sahib/misc/blob/master/bierbogen/beer.pdf

**Comment by zh0uquan** [comment]
Nice, Thank you!
